# Generated by Django 3.2.8 on 2022-10-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('photo', models.CharField(max_length=256)),
            ],
        ),
    ]
