# Generated by Django 3.2.8 on 2022-10-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
