# Generated by Django 3.2.8 on 2022-11-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='back_img',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
