# Generated by Django 3.2.8 on 2022-11-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_back_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='open_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
