# Generated by Django 3.2.8 on 2022-11-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_open_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='back_img',
            field=models.CharField(blank=True, default='https://app3774.acapp.acwing.com.cn/static/superperson/images/menu/hakase.jpg', max_length=256),
        ),
    ]
