# Generated by Django 3.2.8 on 2022-11-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='back_img',
        ),
        migrations.RemoveField(
            model_name='player',
            name='open_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
    ]
