# Generated by Django 3.2.8 on 2022-11-22 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gameclub.models.user_profile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('openid', models.CharField(blank=True, max_length=128)),
                ('photo', models.ImageField(blank=True, upload_to=gameclub.models.user_profile.user_directory_path)),
                ('back', models.ImageField(blank=True, upload_to=gameclub.models.user_profile.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
