# Generated by Django 3.2.8 on 2022-11-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameclub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, upload_to='game/')),
                ('types', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_play', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameclub.gameinfo')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameclub.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='users',
            field=models.ManyToManyField(through='gameclub.UserGameInfo', to='gameclub.UserProfile'),
        ),
    ]
