# Generated by Django 3.2.8 on 2022-11-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameclub', '0002_auto_20221124_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergameinfo',
            name='last_play',
            field=models.DateField(blank=True),
        ),
    ]
