# Generated by Django 3.2.8 on 2023-01-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameclub', '0005_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tool',
            name='permissions',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
