# Generated by Django 3.2.8 on 2023-01-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameclub', '0006_auto_20230110_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='permissions',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
